import ShortBio from '@/components/shortBio'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Container from '@/components/container'
import NavBar from '@/components/navBar'
import SocialAcc from '@/components/socialAcc'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
  
      <body className={`${inter.className} bg-slate-900 text-white h-full`}>
        <Container>
          <div className='h-full flex items-center justify-between'>
            <div>
              <ShortBio />
              <NavBar />
              <SocialAcc />
            </div>
            <div>
              {children}
            </div>
          </div>
        </Container>
      </body>
    </html>
  )
}
